#:schema node_modules/wrangler/config-schema.json
name = "workerA"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]


route = "https://www.evgeniy-ivlev.info/*"
zone_id = "32bbc68c6eb098ba17e5b7cad0364a28"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

