name: Deploy Cloudflare Worker

on:
    push:
        branches:
            - main
            - development # Trigger deployment on changes to the development branch

env:
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}

jobs:
    deploy:
        name: Deploy Cloudflare Worker
        runs-on: ubuntu-latest

        environment: development

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Wrangler CLI
              run: npm install -g wrangler

            - name: Authenticate with Cloudflare
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
              run: |
                  echo -n $CLOUDFLARE_API_TOKEN | wrangler config --api-token

            - name: Publish Worker
              env:
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                  wrangler publish
