
name: Deploy Worker
on:
    push:
        branches:
            - main

env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: development # Specify the environment to access its secrets
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  workingDirectory: ./workerA
